In [2]:
#pip install nump

In [8]:
#import numpy or pip install numpy

In [4]:
type(arr1)

numpy.ndarray

In [1]:
print("kabil")

kabil


In [12]:
import numpy as np
a=np.array([[1,4,5],[34,64,5]])
a
type(a)


numpy.ndarray

In [ ]:
#dimensions of array
a1d=np.array([1,2,3,4,5,6])
a2d=np.array([[1,3,2,5,5],[2,6,7,4,6]])
a3d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6]])
a4d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6],[2,6,7,4,6]])


In [2]:
"kabil"

'kabil'

In [4]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_reshap = arr1d.reshape((3, 4))

print(arr_reshap) 



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import numpy as np
a=np.array([[1,4,5],[34,64,5]])
a

array([[ 1,  4,  5],
       [34, 64,  5]])

In [46]:
#indexing and slicing

In [40]:
import numpy as np
a1d=np.array([1,2,3,4,5,6])
a2d=np.array([[1,3,2,5,5],[2,6,7,4,6]])
a3d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6]])
a4d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6],[2,6,7,4,6]])
print("index",a2d[1,1])
print("slicing",a1d[1:4])
print(a2d)
print(a3d)
print(a4d)



index 6
slicing [2 3 4]
[[1 3 2 5 5]
 [2 6 7 4 6]]
[[1 3 2 5 5]
 [2 6 7 4 6]
 [2 6 7 4 6]]
[[1 3 2 5 5]
 [2 6 7 4 6]
 [2 6 7 4 6]
 [2 6 7 4 6]]


In [50]:
from numpy import random
a=random.randint(50)
a

18

In [46]:
import pandas as pd 
data = {"a":[1,2,3],"b":[779,768,345]}
df=pd.DataFrame(data)
df

a    b
0  1  779
1  2  768
2  3  345

In [59]:
import os
print(os.path.isfile('A:/employee_pfm.csv'))  # return True if the file exists


True


In [48]:
import pandas as pd

emp = pd.read_csv("A:/employee_pfm.csv")
df=pd.DataFrame(emp)
df

team       team_leader  targeted_productivity    smv     wip  over_time  \
0       9      Jane Jackson                   0.75   3.94     NaN        960   
1       7       Sarah Jones                   0.65  30.10   909.0       7080   
2       3  William Anderson                   0.80   4.15     NaN       1440   
3       1      Robert Smith                   0.65  22.53   762.0       5040   
4       4       James Jones                   0.70  30.10   767.0       3300   
..    ...               ...                    ...    ...     ...        ...   
294     3       Emma Taylor                   0.80   4.60     NaN       2400   
295     5      Amelia Brown                   0.75  30.10   788.0       7380   
296     1  Amelia Hernandez                   0.80  22.52  1532.0       6900   
297    10    James Gonzalez                   0.80   3.94     NaN        960   
298     1        Jane Moore                   0.70  26.66  1562.0       6960   

     incentive  idle_time  idle_men  no_of_style_change  ...  \
0            0        0.0         0                   0  ...   
1            0        0.0         0                   1  ...   
2            0        0.0         0                   0  ...   
3            0        0.0         0                   1  ...   
4           50        0.0         0                   1  ...   
..         ...        ...       ...                 ...  ...   
294          0        0.0         0                   0  ...   
295         56        0.0         0                   0  ...   
296         88        0.0         0                   0  ...   
297          0        0.0         0                   0  ...   
298         60        0.0         0                   0  ...   

     department_finishing  department_finishing   department_sweing  \
0                       1                      0                  0   
1                       0                      0                  1   
2                       0                      1                  0   
3                       0                      0                  1   
4                       0                      0                  1   
..                    ...                    ...                ...   
294                     1                      0                  0   
295                     0                      0                  1   
296                     0                      0                  1   
297                     1                      0                  0   
298                     0                      0                  1   

     day_Monday  day_Saturday  day_Sunday  day_Thursday  day_Tuesday  \
0             0             0           0             0            0   
1             0             0           0             1            0   
2             0             0           0             0            0   
3             0             0           0             0            0   
4             1             0           0             0            0   
..          ...           ...         ...           ...          ...   
294           0             0           0             0            0   
295           0             0           0             0            0   
296           0             0           0             0            0   
297           0             0           0             1            0   
298           0             0           0             0            1   

     day_Wednesday  actual_productivity  
0                1             0.755167  
1                0             0.535678  
2                1             0.820833  
3                1             0.581131  
4                0             0.790003  
..             ...                  ...  
294              1             0.900833  
295              1             0.750406  
296              1             0.900147  
297              0             0.771583  
298              0             0.800566  

[299 rows x 27 columns]

In [52]:
df.head()

team       team_leader  targeted_productivity    smv    wip  over_time  \
0     9      Jane Jackson                   0.75   3.94    NaN        960   
1     7       Sarah Jones                   0.65  30.10  909.0       7080   
2     3  William Anderson                   0.80   4.15    NaN       1440   
3     1      Robert Smith                   0.65  22.53  762.0       5040   
4     4       James Jones                   0.70  30.10  767.0       3300   

   incentive  idle_time  idle_men  no_of_style_change  ...  \
0          0        0.0         0                   0  ...   
1          0        0.0         0                   1  ...   
2          0        0.0         0                   0  ...   
3          0        0.0         0                   1  ...   
4         50        0.0         0                   1  ...   

   department_finishing  department_finishing   department_sweing  day_Monday  \
0                     1                      0                  0           0   
1                     0                      0                  1           0   
2                     0                      1                  0           0   
3                     0                      0                  1           0   
4                     0                      0                  1           1   

   day_Saturday  day_Sunday  day_Thursday  day_Tuesday  day_Wednesday  \
0             0           0             0            0              1   
1             0           0             1            0              0   
2             0           0             0            0              1   
3             0           0             0            0              1   
4             0           0             0            0              0   

   actual_productivity  
0             0.755167  
1             0.535678  
2             0.820833  
3             0.581131  
4             0.790003  

[5 rows x 27 columns]

In [54]:
df.tail()

team       team_leader  targeted_productivity    smv     wip  over_time  \
294     3       Emma Taylor                   0.80   4.60     NaN       2400   
295     5      Amelia Brown                   0.75  30.10   788.0       7380   
296     1  Amelia Hernandez                   0.80  22.52  1532.0       6900   
297    10    James Gonzalez                   0.80   3.94     NaN        960   
298     1        Jane Moore                   0.70  26.66  1562.0       6960   

     incentive  idle_time  idle_men  no_of_style_change  ...  \
294          0        0.0         0                   0  ...   
295         56        0.0         0                   0  ...   
296         88        0.0         0                   0  ...   
297          0        0.0         0                   0  ...   
298         60        0.0         0                   0  ...   

     department_finishing  department_finishing   department_sweing  \
294                     1                      0                  0   
295                     0                      0                  1   
296                     0                      0                  1   
297                     1                      0                  0   
298                     0                      0                  1   

     day_Monday  day_Saturday  day_Sunday  day_Thursday  day_Tuesday  \
294           0             0           0             0            0   
295           0             0           0             0            0   
296           0             0           0             0            0   
297           0             0           0             1            0   
298           0             0           0             0            1   

     day_Wednesday  actual_productivity  
294              1             0.900833  
295              1             0.750406  
296              1             0.900147  
297              0             0.771583  
298              0             0.800566  

[5 rows x 27 columns]

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   team                   299 non-null    int64  
 1   team_leader            299 non-null    object 
 2   targeted_productivity  299 non-null    float64
 3   smv                    299 non-null    float64
 4   wip                    174 non-null    float64
 5   over_time              299 non-null    int64  
 6   incentive              299 non-null    int64  
 7   idle_time              299 non-null    float64
 8   idle_men               299 non-null    int64  
 9   no_of_style_change     299 non-null    int64  
 10  no_of_workers          299 non-null    float64
 11  month                  299 non-null    int64  
 12  quarter_Quarter1       299 non-null    int64  
 13  quarter_Quarter2       299 non-null    int64  
 14  quarter_Quarter3       299 non-null    int64  
 15  quarte

In [12]:
import pandas as pd

df = pd.read_csv("A:/employee_pfm.csv")
empqtr = df.groupby(['quarter_Quarter1', 'quarter_Quarter2', 'quarter_Quarter3', 'quarter_Quarter4', 'quarter_Quarter5']).size()
grpqrt=pd.DataFrame(empqtr)
grpqrt


0
quarter_Quarter1 quarter_Quarter2 quarter_Quarter3 quarter_Quarter4 quarter_Quarter5    
0                0                0                0                1                 10
                                                   1                0                 65
                                  1                0                0                 47
                 1                0                0                0                 78
1                0                0                0                0                 99

In [16]:
#employee counts by day
day_counts = df[['day_Monday', 'day_Tuesday', 'day_Wednesday', 'day_Thursday', 'day_Saturday', 'day_Sunday']].sum()
print("Employee counts by day:")
dc=pd.DataFrame(day_counts)
dc


Employee counts by day:


0
day_Monday     42
day_Tuesday    51
day_Wednesday  65
day_Thursday   56
day_Saturday   39
day_Sunday     46

In [26]:
# Filter by Departments
finishing_dept = df[df['department_finishing'] == 1]
sweing_dept = df[df['department_sweing'] == 1]

print(f"Finishing department employees count: {len(finishing_dept)}")
print(f"Sweing department employees count: {len(sweing_dept)}")


Finishing department employees count: 66
Sweing department employees count: 174


In [32]:
df['Total_Days_Worked'] = df[['day_Monday', 'day_Tuesday', 'day_Wednesday', 'day_Thursday', 'day_Saturday', 'day_Sunday']].sum(axis=1)
da=df.head()
frame=pd.DataFrame(da)
frame


team       team_leader  targeted_productivity    smv    wip  over_time  \
0     9      Jane Jackson                   0.75   3.94    NaN        960   
1     7       Sarah Jones                   0.65  30.10  909.0       7080   
2     3  William Anderson                   0.80   4.15    NaN       1440   
3     1      Robert Smith                   0.65  22.53  762.0       5040   
4     4       James Jones                   0.70  30.10  767.0       3300   

   incentive  idle_time  idle_men  no_of_style_change  ...  \
0          0        0.0         0                   0  ...   
1          0        0.0         0                   1  ...   
2          0        0.0         0                   0  ...   
3          0        0.0         0                   1  ...   
4         50        0.0         0                   1  ...   

   department_finishing   department_sweing  day_Monday  day_Saturday  \
0                      0                  0           0             0   
1                      0                  1           0             0   
2                      1                  0           0             0   
3                      0                  1           0             0   
4                      0                  1           1             0   

   day_Sunday  day_Thursday  day_Tuesday  day_Wednesday  actual_productivity  \
0           0             0            0              1             0.755167   
1           0             1            0              0             0.535678   
2           0             0            0              1             0.820833   
3           0             0            0              1             0.581131   
4           0             0            0              0             0.790003   

   Total_Days_Worked  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1  

[5 rows x 28 columns]

In [45]:
deptsmry = df.groupby(['department_finishing', 'department_sweing'])['Total_Days_Worked'].sum()
print("Total Days Worked per Department:")
dw=pd.DataFrame(deptsmry)
dw


Total Days Worked per Department:


Total_Days_Worked
department_finishing department_sweing                   
0                    0                                 59
                     1                                174
1                    0                                 66

In [63]:
df.to_csv('A:/employee_pfm.csv')
df

team       team_leader  targeted_productivity    smv     wip  over_time  \
0       9      Jane Jackson                   0.75   3.94     NaN        960   
1       7       Sarah Jones                   0.65  30.10   909.0       7080   
2       3  William Anderson                   0.80   4.15     NaN       1440   
3       1      Robert Smith                   0.65  22.53   762.0       5040   
4       4       James Jones                   0.70  30.10   767.0       3300   
..    ...               ...                    ...    ...     ...        ...   
294     3       Emma Taylor                   0.80   4.60     NaN       2400   
295     5      Amelia Brown                   0.75  30.10   788.0       7380   
296     1  Amelia Hernandez                   0.80  22.52  1532.0       6900   
297    10    James Gonzalez                   0.80   3.94     NaN        960   
298     1        Jane Moore                   0.70  26.66  1562.0       6960   

     incentive  idle_time  idle_men  no_of_style_change  ...  \
0            0        0.0         0                   0  ...   
1            0        0.0         0                   1  ...   
2            0        0.0         0                   0  ...   
3            0        0.0         0                   1  ...   
4           50        0.0         0                   1  ...   
..         ...        ...       ...                 ...  ...   
294          0        0.0         0                   0  ...   
295         56        0.0         0                   0  ...   
296         88        0.0         0                   0  ...   
297          0        0.0         0                   0  ...   
298         60        0.0         0                   0  ...   

     department_finishing   department_sweing  day_Monday  day_Saturday  \
0                        0                  0           0             0   
1                        0                  1           0             0   
2                        1                  0           0             0   
3                        0                  1           0             0   
4                        0                  1           1             0   
..                     ...                ...         ...           ...   
294                      0                  0           0             0   
295                      0                  1           0             0   
296                      0                  1           0             0   
297                      0                  0           0             0   
298                      0                  1           0             0   

     day_Sunday  day_Thursday  day_Tuesday  day_Wednesday  \
0             0             0            0              1   
1             0             1            0              0   
2             0             0            0              1   
3             0             0            0              1   
4             0             0            0              0   
..          ...           ...          ...            ...   
294           0             0            0              1   
295           0             0            0              1   
296           0             0            0              1   
297           0             1            0              0   
298           0             0            1              0   

     actual_productivity  Total_Days_Worked  
0               0.755167                  1  
1               0.535678                  1  
2               0.820833                  1  
3               0.581131                  1  
4               0.790003                  1  
..                   ...                ...  
294             0.900833                  1  
295             0.750406                  1  
296             0.900147                  1  
297             0.771583                  1  
298             0.800566                  1  

[299 rows x 28 columns]